# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votos',
            name='candidatov',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='votos.Candidato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votos',
            name='distritov',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='votos.Distrito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='edadc',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nombrec',
            field=models.CharField(default='Nombre canditdato', max_length=50),
        ),
    ]
