# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0002_auto_20171124_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='nombrec',
            field=models.CharField(default='Nombre candidato', max_length=50),
        ),
    ]
